name:                inf-backprop
version:             0.2.0.0
license:             BSD3
author:              "Alexey Tochin"
maintainer:          "Alexey.Tochin@gmail.com"
copyright:           "2023 Alexey Tochin"

extra-source-files:
  - CHANGELOG.md

extra-doc-files:
  - doc/images/*.png

synopsis:            Automatic differentiation and backpropagation.
category:            Mathematics

description: |
  ![Second order derivative of a composition](docs/doc/images/composition_second_derivative.png)

  Automatic differentiation and backpropagation.
  We do not attract gradient tape.
  Instead, the differentiation operator is defined directly as a map between differentiable function objects.
  Such functions are to be combined in arrow style using '(>>>)', '(***)', 'first', etc.
  
  The original purpose of the package is an automatic backpropagation differentiation component
  for a functional type-dependent library for deep machine learning.
  See [tutorial](docs/InfBackprop-Tutorial.html) details.
  
dependencies:
  - base >= 4.7 && < 5
  - numhask
  - isomorphism-class
  - monad-logger
  - text
  - transformers
  - comonad
  - simple-expr
  - profunctors
  - optics
  - finite-typelits
  - vector
  - vector-sized
  - fixed-vector
  - primitive
  - Stream
  - deepseq
  - ghc-prim
  - data-fix
  - safe
  - extra
  - unordered-containers

ghc-options:
#  - -w
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs:
#    - src
    - src2
  default-extensions:
    - NoImplicitPrelude
    - GADTs
    - TypeFamilies
    - MultiParamTypeClasses
    - FlexibleInstances
    - ScopedTypeVariables
    - ConstraintKinds
    - RankNTypes
    - InstanceSigs
    - TupleSections
    - FlexibleContexts
    - DeriveFunctor
    - TypeOperators
    - BangPatterns

tests:
  doctests:
    source-dirs:        doctests
    main:               Main.hs
    ghc-options:
      - -w
      - -fno-warn-missing-methods
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - simple-expr
      - doctest